language: java
jdk:
  - openjdk12
sudo: false
script: sh scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 869e7c4b-f121-4132-ae1a-b8718613b0e1
env:
  global:
    - CODECOV_TOKEN=:869e7c4b-f121-4132-ae1a-b8718613b0e1